### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by QiueY514** [jkli1998/DRM#3]
Hi, the link of scene graphs for VG dataset in [DATASET.md](https://github.com/jkli1998/DRM/blob/main/DATASET.md) is not access. Could you update the link? Thanks!

**Comment by jkli1998** [comment]
Thanks for the reminder. We have updated the link in DATASET.md.

**Comment by QiueY514** [comment]
> Thanks for the reminder. We have updated the link in DATASET.md.

Thank you for your reply. But there are still no files in this link (the OneDrive link of scene graphs of VG dataset).
![20240903101530](https://github.com/user-attachments/assets/62279613-f875-46dc-9c64-4b0f6eccbedc)
